### ISSUE TITLE
Post-commit hook fails: Click will abort further execution because Python 3 was configured to use ASCII as encoding for the environment

### ISSUE THREAD

**Issue by fapdash** [EMPRI-DEVOPS/git-privacy#13]
```
$ git commit -am "test foo"
Traceback (most recent call last):
  File "/home/fap/.local/bin/git-privacy", line 8, in <module>
    sys.exit(cli())
  File "/home/fap/.local/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/fap/.local/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/fap/.local/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/fap/.local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/fap/.local/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/fap/.local/lib/python3.6/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/fap/.local/lib/python3.6/site-packages/gitprivacy/gitprivacy.py", line 225, in do_redate
    amendrewriter.rewrite()
  File "/home/fap/.local/lib/python3.6/site-packages/gitprivacy/rewriter/amendrewriter.py", line 35, in rewrite
    GITPRIVACY_ACTIVE="yes",
  File "/home/fap/.local/lib/python3.6/site-packages/git/cmd.py", line 822, in execute
    raise GitCommandError(command, status, stderr_value, stdout_value)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(1)
  cmdline: git commit --amend --allow-empty --date="Sun May 31 00:00:00 2020 +0200" --message=test foo
 --message=GitPrivacy: 5biz5mr9FqAkZVPtAqiE4WRJ+aFPLan3mNLtaVf1cNqRYXayU14/FS3q6XTSy/5dOzNGZ5j4IAQtKNqarRMV3/xs8BSCZvM2Ww==
  stderr: 'Traceback (most recent call last):
  File "/home/fap/.local/bin/git-privacy", line 8, in <module>
    sys.exit(cli())
  File "/home/fap/.local/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/fap/.local/lib/python3.6/site-packages/click/core.py", line 760, in main
    _verify_python3_env()
  File "/home/fap/.local/lib/python3.6/site-packages/click/_unicodefun.py", line 130, in _verify_python3_env
    " mitigation steps.{}".format(extra)
RuntimeError: Click will abort further execution because Python 3 was configured to use ASCII as encoding for the environment. Consult https://click.palletsprojects.com/python3/ for mitigation steps.

This system supports the C.UTF-8 locale which is recommended. You might be able to resolve your issue by exporting the following environment variables:

    export LC_ALL=C.UTF-8
    export LANG=C.UTF-8'
[master e4c7949] test foo
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 foo
```

```
$ locale
LANG=en_US.UTF8
LANGUAGE=en_US.UTF8
LC_CTYPE="en_US.UTF8"
LC_NUMERIC="en_US.UTF8"
LC_TIME="en_US.UTF8"
LC_COLLATE="en_US.UTF8"
LC_MONETARY="en_US.UTF8"
LC_MESSAGES="en_US.UTF8"
LC_PAPER="en_US.UTF8"
LC_NAME="en_US.UTF8"
LC_ADDRESS="en_US.UTF8"
LC_TELEPHONE="en_US.UTF8"
LC_MEASUREMENT="en_US.UTF8"
LC_IDENTIFICATION="en_US.UTF8"
LC_ALL=en_US.UTF8
```

**Comment by fapdash** [comment]
Not sure what changed, I'm running git-privacy version 1.4.1 on a Ubuntu 18.04 machine.
Git-privacy worked on this machine before without any problems.

**Comment by cburkert** [comment]
Unfortunately, I'm not able to reproduce the issue on Ubuntu 18.04 with the said locales.
Does the issue show up in v1.4.0?

**Comment by cburkert** [comment]
@fapdash Did you experience this issue lately? Otherwise you can close this.

**Comment by fapdash** [comment]
This is still happening, but the hook redacts the timestamp anyways.
If nobody else is experiencing this problem I guess we can close this.
